### PR TITLE
DONT-MERGE: Can't properly integrate Stylable into sample-monorepo

### PR DESCRIPTION
**Pull request by Zombiefruit**
Just opening a PR for this to make it easier to compare and discuss the issue.

I'm trying to get Stylable working with a sample-monorepo project. I've added dependencies for `stylable` and `stylable-webpack-plugun`, added a `globals.d.ts` file in the `src` folder of `components` (where I'm using Stylable), added `StylableWebpackConfig` to the `webpack.config.js` file, but no dice. 

When trying to start the project it doesn't resolve the `st.css` file properly. If I build the Stylable file manually (using the Stylable cli) into the `./dist`, it works, but isn't that the point of using webpack with the plugin? 

Not sure what I'm doing wrong here and would appreciate some help.

@tomrav @AviVahl @barak007

### CODE REVIEW

**Comment by tomrav** [comment]
You're using an ancient version of Stylable, I imagine you intended on using `@stylable/core` instead of `stylable`.

**Comment by Zombiefruit** [comment]
> You're using an ancient version of Stylable, I imagine you intended on using `@stylable/core` instead of `stylable`.

Ah, great, will try with `@stylable/core`. Was just following this btw: https://stylable.io/docs/getting-started/install-configure#install-stylable-to-work-with-an-existing-project 

So should probably be updated if it's not a TODO yet

**Comment by tomrav** [comment]
> > You're using an ancient version of Stylable, I imagine you intended on using `@stylable/core` instead of `stylable`.
> 
> Ah, great, will try with `@stylable/core`. Was just following this btw: https://stylable.io/docs/getting-started/install-configure#install-stylable-to-work-with-an-existing-project
> 
> So should probably be updated if it's not a TODO yet

That's terrible on our part, will fix and update.

**Comment by AviVahl** [comment]
When installing stuff, always check for installation warnings. In this case peer deps warnings.
Issue is resolved then?

**Pull request closed without merging**
